DotNetQuiz/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace DotNetQuiz.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

DotNetQuiz/Views/Shared/_Html5Boilerplate.cshtml
<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>@ViewBag.Title</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" href="@Url.Content("~/favicon.ico")">
	<link rel="apple-touch-icon" href="@Url.Content("~/apple-touch-icon.png")">
	<link rel="stylesheet" href="@Url.Content("~/Content/style.css?v=2")">
    <link rel="stylesheet" media="handheld" href="@Url.Content("~/Content/handheld.css?v=2")">
	<script src="@Url.Content("~/Scripts/libs/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
	<div id="container">
		<header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
		</header>

		<div id="main" role="main">
            @RenderBody()
		</div>

		<footer>

		</footer>
	</div>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>
	<script type="text/javascript">	    !window.jQuery && document.write(unescape('%3Cscript src="@Url.Content("~/Scripts/libs/jquery-1.5.1.min.js")"%3E%3C/script%3E'))</script>
	<script src="@Url.Content("~/Scripts/plugins.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/script.js")" type="text/javascript"></script>
	<!--[if lt IE 7 ]>
	<script src="@Url.Content("~/Scripts/libs/dd_belatedpng.js")"></script>
	<script> DD_belatedPNG.fix('img, .png_bg');</script>
	<![endif]-->
	<script type="text/javascript">
	    var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
	    (function (d, t) {
	        var g = d.createElement(t), s = d.getElementsByTagName(t)[0]; g.async = 1;
	        g.src = ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js';
	        s.parentNode.insertBefore(g, s)
	    } (document, 'script'));
	</script>
</body>
</html>

DotNetQuiz/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.0rc3.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/Site.Mobile.css")" />
    <script src="@Url.Content("~/Scripts/jquery-1.6.3.min.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).bind("mobileinit", function () {
            // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
            // when navigating from a mobile to a non-mobile page), hence disabling it.
            $.mobile.ajaxEnabled = false;
        });
    </script>

@*
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")">
    <link rel="apple-touch-icon" href="@Url.Content("~/apple-touch-icon.png")">*@

    <script src="@Url.Content("~/Scripts/jquery.mobile-1.0rc3.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="DotNetQuizPage" data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")
        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>
        <div id="MainContent" data-role="content">
            @RenderSection("featured", false)
            @RenderBody()
        </div>
    </div>
   @RenderSection("scripts")
</body>
</html>

DotNetQuiz/Views/Shared/_Layout.cshtml
<!doctype html>
@*<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->*@
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name = "viewport" content = "width = device-width" />
    <title>@ViewBag.Title</title>

	<meta name="description" content="">
	<meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="shortcut icon" href="@Url.Content("~/favicon.ico")">
	<link rel="apple-touch-icon" href="@Url.Content("~/apple-touch-icon.png")">
	<link rel="stylesheet" href="@Url.Content("~/Content/style.css?v=2")">
    <link rel="stylesheet" media="handheld" href="@Url.Content("~/Content/handheld.css?v=2")">
	<script src="@Url.Content("~/Scripts/libs/modernizr-1.7.min.js")" type="text/javascript"></script>

    <!--[if IE]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<!--[if lte IE 7]>
	<script src="js/IE8.js" type="text/javascript"></script><![endif]-->


	
	 <link href="@Url.Content("~/Content/Main.css")" rel="stylesheet" type="text/css" />

     
    

    @RenderSection("AdditionalScripts")
</head>


    <body>
    @Html.Partial("_ViewSwitcher")
<header id="titleBox" class="centerbox">

<h1>DotNet Quiz</h1>

<nav id="headerMenu">

</nav>

</header>



<article id="main" class="centerbox">

<section id="quizBox">
@RenderBody()
</section>
</article>


    <footer>
        @RenderSection("footer")
    </footer>
    @*<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>*@
    <script src="~/Scripts/jquery-1.6.4.min.js" type="text/javascript"></script>
	<script type="text/javascript">	    !window.jQuery && document.write(unescape('%3Cscript src="@Url.Content("~/Scripts/libs/jquery-1.5.1.min.js")"%3E%3C/script%3E'))</script>
	<script src="@Url.Content("~/Scripts/plugins.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/script.js")" type="text/javascript"></script>
	<!--[if lt IE 7 ]>
	<script src="@Url.Content("~/Scripts/libs/dd_belatedpng.js")"></script>
	<script> DD_belatedPNG.fix('img, .png_bg');</script>
	<![endif]-->
	<script type="text/javascript">
	    var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
	    (function (d, t) {
	        var g = d.createElement(t), s = d.getElementsByTagName(t)[0]; g.async = 1;
	        g.src = ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js';
	        s.parentNode.insertBefore(g, s);
	    } (document, 'script'));
	</script>
@RenderSection("scripts")
</body>
</html>

DotNetQuiz/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}